package cn.zy.apps.tools.test ;

import javax.persistence.Column ;
import javax.persistence.Entity ;
import javax.persistence.FetchType ;
import javax.persistence.GeneratedValue ;
import javax.persistence.GenerationType ;
import javax.persistence.Id ;
import javax.persistence.JoinColumn ;
import javax.persistence.OneToOne ;
import javax.persistence.Table ;

import cn.zy.apps.tools.jpa.FieldDesc ;

/**
 * SystemUser generated by hbm2java
 */
@Entity
@Table(name = "system_user")
public class SystemUser extends CommBean {


    private static final long serialVersionUID = 8238708907376609336L ;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer id ;

    @Column(name = "account", length = 10)
    @FieldDesc(name = "是否管理员", desc = "0:否;1:是")
    private String account ;

    @Column(name = "pwd", length = 10)
    @FieldDesc(name = "密码", isShow = false)
    private String pwd ;

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "staff_info_id")
    @FieldDesc(name = "员工", mapping = "name.ss")
    private StaffInfo staffInfo ;

    @Column(name = "staff_info_id", updatable = false, insertable = false)
    private Integer staffInfoId ;

    @Column(name = "is_admin")
    @FieldDesc(name = "是否管理员", desc = "0:否;1:是")
    private Integer isAdmin ;

    // 业务员
    @Column(name = "is_biz_man")
    @FieldDesc(name = "是否业务员", desc = "0:否;1:是")
    private Integer isBizMan ;

    // 是否理货员
    @Column(name = "is_goods_man")
    @FieldDesc(name = "是否理货员", desc = "0:否;1:是")
    private Integer isGoodsMan ;

    // 是否采购员
    @Column(name = "is_stock_man")
    @FieldDesc(name = "是否采购员", desc = "0:否;1:是")
    private Integer isStockMan ;

    // 是否运输人
    @Column(name = "is_transport_man")
    @FieldDesc(name = " 是否运输人", desc = "0:否;1:是")
    private Integer isTransportMan ;

    @Column(name = "text")
    @FieldDesc(name = "备注")
    private String text ;

    public Integer getId() {
        return id ;
    }

    public void setId(Integer id) {
        this.id = id ;
    }

    public String getAccount() {
        return account ;
    }

    public void setAccount(String account) {
        this.account = account ;
    }

    public String getPwd() {
        return pwd ;
    }

    public void setPwd(String pwd) {
        this.pwd = pwd ;
    }

    public StaffInfo getStaffInfo() {
        return staffInfo ;
    }

    public void setStaffInfo(StaffInfo staffInfo) {
        this.staffInfo = staffInfo ;
    }

    public Integer getStaffInfoId() {
        return staffInfoId ;
    }

    public void setStaffInfoId(Integer staffInfoId) {
        this.staffInfoId = staffInfoId ;
    }

    public Integer getIsAdmin() {
        return isAdmin ;
    }

    public void setIsAdmin(Integer isAdmin) {
        this.isAdmin = isAdmin ;
    }

    public Integer getIsBizMan() {
        return isBizMan ;
    }

    public void setIsBizMan(Integer isBizMan) {
        this.isBizMan = isBizMan ;
    }

    public Integer getIsGoodsMan() {
        return isGoodsMan ;
    }

    public void setIsGoodsMan(Integer isGoodsMan) {
        this.isGoodsMan = isGoodsMan ;
    }

    public Integer getIsStockMan() {
        return isStockMan ;
    }

    public void setIsStockMan(Integer isStockMan) {
        this.isStockMan = isStockMan ;
    }

    public Integer getIsTransportMan() {
        return isTransportMan ;
    }

    public void setIsTransportMan(Integer isTransportMan) {
        this.isTransportMan = isTransportMan ;
    }

    public String getText() {
        return text ;
    }

    public void setText(String text) {
        this.text = text ;
    }

}
